tap "homebrew/bundle"

brew "oh-my-posh"
brew "go"

cask "keka"
cask "iina"
cast "motrix"
cask "ghostty"
cask "aldente"
cask "spotify"
cask "discord"
cask "whatsapp"
cask "tailscale"
cask "visual-studio-code"
cask "font-fira-code-nerd-font" 
cask "firefox@developer-edition"